### ISSUE TITLE
tts server突然没声音了

### ISSUE THREAD

**Issue by shizuyounv** [jing332/tts-server-go#11]
![Screenshot_2023-01-15-00-44-36-726_io legado app release](https://user-images.githubusercontent.com/52289116/212484372-e6dd9c60-fb9f-479b-a60c-923f04e4f03d.jpg)
如图，上面的那个tts server用着用着没声音了，我看阅读是能一条一条往下念的，我看通知栏也是一条一条往下念的。现在用的网络导入的大声朗读是能用的

**Comment by jing332** [comment]
啥信息没有你叫我如何排查？
自行看日志

**Comment by shizuyounv** [comment]
![Screenshot_2023-01-15-08-54-09-760_com github jing332 tts_server_android](https://user-images.githubusercontent.com/52289116/212503593-71133ccf-2b71-41ce-b550-3100e43d52eb.jpg)
![Screenshot_2023-01-15-08-54-15-615_io legado app release](https://user-images.githubusercontent.com/52289116/212503599-8b6297dc-3f78-4629-ab9e-fbed9a9c0be6.jpg)
呃呃，好像没看到有日志

**Comment by jing332** [comment]
你这是Server的日志界面，左上角切到系统TTS

**Comment by shizuyounv** [comment]
![Uploading Screenshot_2023-01-15-08-58-46-706_com.github.jing332.tts_server_android.jpg…]()

**Comment by shizuyounv** [comment]
![Screenshot_2023-01-15-08-58-46-706_com github jing332 tts_server_android](https://user-images.githubusercontent.com/52289116/212503719-f14b45b5-c156-4ba2-87bb-e5216c7d5d96.jpg)

**Comment by jing332** [comment]
creation接口已失效

**Comment by shizuyounv** [comment]
哦哦，谢谢，解决了
