### ISSUE TITLE
功能请求

### ISSUE THREAD

**Issue by qi-mooo** [jing332/tts-server-go#14]
希望增加像 tts-server-android 一样的旁白/对话功能，一是因为有Android x86平板，而tts-server-android在我的设备上fc，二是因为tts-server-android使用系统tts模式时并不支持预存导致播放经常卡顿。其次是我的设备经常杀后台导致播放停顿，所以我一直都是跑的 tts-server-go

**Comment by jing332** [comment]
@qi-mooo 精力有限，见谅

**Comment by qi-mooo** [comment]
> @qi-mooo 精力有限，见谅

好的，那是否可以在 tts-server-android releases 的时候向ndk增加 Android x86 支持

**Comment by jing332** [comment]
OK 这倒是容易。

**Comment by jing332** [comment]
> 


> > @qi-mooo 精力有限，见谅
> 
> 好的，那是否可以在 tts-server-android releases 的时候向ndk增加 Android x86 支持

x86和x86_64都加上了，你可以先上Actions下载

**Comment by qi-mooo** [comment]
> > 
> 
> > > @qi-mooo 精力有限，见谅
> > 
> > 
> > 好的，那是否可以在 tts-server-android releases 的时候向ndk增加 Android x86 支持
> 
> x86和x86_64都加上了，你可以先上Actions下载

![屏幕截图_20230209_102629](https://user-images.githubusercontent.com/59095213/217701812-36fe68bf-b3b1-43a4-8523-7cfbf082229e.png)
很棒完美运行
