### ISSUE TITLE
是否能提供音频文件生成和下载功能

### ISSUE THREAD

**Issue by kchen0x** [jing332/tts-server-go#7]
目前只能通过网页进行音频播放，是否能够提供音频文件生成，和下载到本地磁盘的功能？

**Comment by jing332** [comment]
如要下载音频建议自行POST `api/azure` ，可以自定义SSML

**Comment by kchen0x** [comment]
能辛苦举个例子吗😘

**Comment by jing332** [comment]
直接Chrome F12对网页抓包就可以看到测试的请求。

**Comment by jing332** [comment]
PostMain 示例请求： https://documenter.getpostman.com/view/8342185/2s8Z6vYZgM

**Comment by kchen0x** [comment]
Thank U, it works!
