### ISSUE TITLE
我该如何下载生成的音频？

### ISSUE THREAD

**Issue by wcsanshu** [jing332/tts-server-go#9]

**Comment by jing332** [comment]
#7

**Comment by wcsanshu** [comment]
感谢！

**Comment by xp12047** [comment]
谁能再给个简单点的教程。我不会curl，直接复制示例在cmd上不管用呢？

**Comment by jing332** [comment]
> 谁能再给个简单点的教程。我不会curl，直接复制示例在cmd上不管用呢？

安装postman直接导入，或者文档右上角切换语言如powershell

**Comment by xp12047** [comment]
> > 谁能再给个简单点的教程。我不会curl，直接复制示例在cmd上不管用呢？
> 
> 安装postman直接导入，或者文档右上角切换语言如powershell

谢谢，我试下吧

**Comment by xp12047** [comment]
> > 谁能再给个简单点的教程。我不会curl，直接复制示例在cmd上不管用呢？
> 
> 安装postman直接导入，或者文档右上角切换语言如powershell

谢谢大佬打扰你了。现在好用了 😄 ,可我想改成mp3。那个`audio/mp3;codec=mp3`不行呢？
